[package]
name = "ploot"
version = "0.2.1"
authors = ["Michael Mogenson <michael.mogenson@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.8.0"
termion = "1.5.5"
float-pretty-print = "0.1.0"
structopt = "0.3.9"
